### ISSUE TITLE
Fix CSS or make it responsive

### ISSUE THREAD

**Issue by losier** [losier/bhagavad#1]
Need to fix css for this project or help me to make it responsive

**Comment by Rishav1707** [comment]
Would you like a responsive website? @losier

**Comment by losier** [comment]
Yes I would love to see one @Rishav1707

**Comment by Rishav1707** [comment]
Let me try this once

**Comment by Rishav1707** [comment]
I want some time to fix this issue

**Comment by losier** [comment]
sure take you time just let me push some of my work then you can start working and please dont mind if you see some weird css my css skills are ded
@Rishav1707

**Comment by losier** [comment]
Done now you can take your time 
Radhe Radhe 🙏

**Comment by Rishav1707** [comment]
> sure take you time just let me push some of my work then you can start working and please dont mind if you see some weird css my css skills are ded @Rishav1707

Sure sure 😊
